#!/usr/bin/env python3
"""Visualize skills-graph.json → Mermaid flowchart + stats report."""

import json
from pathlib import Path
from collections import Counter

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
GRAPH_PATH = REPO_ROOT / 'skills-graph.json'
MMD_PATH = REPO_ROOT / 'docs' / 'skills-graph.mmd'
STATS_PATH = REPO_ROOT / 'docs' / 'graph-stats.md'

# ── Plugin color palette ────────────────────────────────────────────────

PLUGIN_COLORS = {
    'ideal-dev-workflow': '#3b82f6',
    'ideal-ppt-suite': '#8b5cf6',
    'ideal-document-workflow': '#14b8a6',
    'ideal-knowledge-base': '#10b981',
    'panel-review': '#f59e0b',
    'skill-builder': '#ef4444',
    'baoyu-image-gen': '#ec4899',
    'ideal-deep-research': '#6366f1',
    'ideal-dify-generator': '#06b6d4',
    'ideal-ralph': '#84cc16',
    'ideal-lab-maintainer': '#6b7280',
}

EDGE_STYLES = {
    'prerequisite': '-->',
    'embeds': '==>',
    'enhancement': '-.->',
    'produces_for': '-.->',
    'alternative': '<-->',
}

EDGE_LABELS = {
    'prerequisite': 'requires',
    'embeds': 'calls',
    'enhancement': 'enhances',
    'produces_for': 'produces for',
    'alternative': 'alternative',
}


def load_graph():
    return json.loads(GRAPH_PATH.read_text(encoding='utf-8'))


def generate_mermaid(graph):
    """Generate Mermaid flowchart."""
    lines = ['%% Skills Graph — auto-generated from skills-graph.json',
             '%% Generated by scripts/build-graph/visualize-graph.py',
             '',
             'graph TD']

    nodes = graph['nodes']
    edges = graph['edges']

    # Group nodes by plugin
    plugin_groups = {}
    for n in nodes:
        p = n['plugin']
        if p not in plugin_groups:
            plugin_groups[p] = []
        plugin_groups[p].append(n)

    # Generate subgraphs per plugin
    for plugin, group in sorted(plugin_groups.items()):
        color = PLUGIN_COLORS.get(plugin, '#999999')
        lines.append(f'  subgraph "{plugin}"')
        for n in group:
            node_id = sanitize_id(n['id'])
            label = n['name']
            arity_marker = ''
            if n['arity'] == 'orchestrator':
                arity_marker = ' ⚙'
            elif n['arity'] == 'phase':
                arity_marker = ' ◆'
            lines.append(f'    {node_id}["{label}{arity_marker}"]')
        lines.append(f'    style {plugin.replace("-", "_")} fill:none,stroke:{color}')
        lines.append('  end')
        lines.append('')

    # Generate edges
    for e in edges:
        src = sanitize_id(e['source'])
        tgt = sanitize_id(e['target'])
        style = EDGE_STYLES.get(e['relation'], '-->')
        label = EDGE_LABELS.get(e['relation'], e['relation'])
        lines.append(f'  {src} {style}|{label}| {tgt}')

    # Group edge types in legend
    lines.append('')
    lines.append('  %% Legend')
    lines.append('  %% -->  : prerequisite (A must run before B)')
    lines.append('  %% ==>  : embeds (A spawns B)')
    lines.append('  %% -.-> : enhancement / produces_for (A improves/feeds B)')
    lines.append('  %% <--> : alternative (A and B are interchangeable)')

    return '\n'.join(lines)


def sanitize_id(node_id):
    """Convert node ID to valid Mermaid identifier."""
    return node_id.replace('/', '_').replace('-', '_').replace('.', '_')


def generate_stats(graph):
    """Generate markdown stats report."""
    nodes = graph['nodes']
    edges = graph['edges']
    meta = graph['metadata']

    lines = [
        '# Skills Graph Statistics',
        '',
        f'Generated: {meta["generated_at"]}',
        '',
        '## Overview',
        '',
        f'| Metric | Value |',
        f'|--------|-------|',
        f'| Total Skills | {len(nodes)} |',
        f'| Total Edges | {len(edges)} |',
        f'| Plugins Covered | {len(set(n["plugin"] for n in nodes))} |',
        '',
        '## Arity Distribution',
        '',
        '| Arity | Count |',
        '|-------|-------|',
    ]
    for arity, count in sorted(meta['arity_distribution'].items(), key=lambda x: -x[1]):
        lines.append(f'| {arity} | {count} |')

    lines.extend([
        '',
        '## Edge Type Distribution',
        '',
        '| Relation | Count |',
        '|----------|-------|',
    ])
    for rel, count in sorted(meta['relation_distribution'].items(), key=lambda x: -x[1]):
        lines.append(f'| {rel} | {count} |')

    # Per-plugin breakdown
    lines.extend(['', '## Skills per Plugin', '', '| Plugin | Skills |', '|--------|--------|'])
    plugin_counts = Counter(n['plugin'] for n in nodes)
    for plugin, count in plugin_counts.most_common():
        lines.append(f'| {plugin} | {count} |')

    # Orphan skills
    orphans = meta.get('orphan_skills', [])
    if orphans:
        lines.extend([
            '',
            '## Orphan Skills (no edges)',
            '',
            'These skills have no incoming or outgoing edges in the graph:',
            '',
        ])
        for o in orphans:
            lines.append(f'- `{o}`')

    # Longest path (by plugin)
    lines.extend([
        '',
        '## Critical Paths (by plugin)',
        '',
    ])
    for plugin_name in sorted(set(n['plugin'] for n in nodes)):
        prereq_edges = [e for e in edges
                        if e['relation'] == 'prerequisite'
                        and e['source'].startswith(plugin_name)]
        if prereq_edges:
            # Simple topological chain
            chain_nodes = set()
            for e in prereq_edges:
                chain_nodes.add(e['source'])
                chain_nodes.add(e['target'])
            chain_nodes = [n for n in chain_nodes if n.startswith(plugin_name)]
            lines.append(f'- **{plugin_name}**: {len(chain_nodes)} skills in prerequisite chain ({len(prereq_edges)} prerequisite edges)')

    return '\n'.join(lines)


def main():
    graph = load_graph()

    # Write Mermaid
    mmd = generate_mermaid(graph)
    MMD_PATH.write_text(mmd, encoding='utf-8')
    print(f"✓ Wrote Mermaid diagram to {MMD_PATH}")

    # Write stats
    stats = generate_stats(graph)
    STATS_PATH.write_text(stats, encoding='utf-8')
    print(f"✓ Wrote stats report to {STATS_PATH}")


if __name__ == '__main__':
    main()